### ISSUE TITLE
Merge strategy

### ISSUE THREAD

**Issue by Akryum** [samuelantonioli/vue-static#1]
It would be great to merge data with a [Custom merge strategy](https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies) so it may be used with `extends`/`mixins`. You may reuse the strategy for `data`: `Vue.config.optionMergeStrategies.data`.

**Comment by samuelantonioli** [comment]
Great idea.

This should do and enables users to use custom merge strategies for `static`. Would be happy about some feedback.

```javascript
function install(Vue) {
    if (typeof(Vue.config.optionMergeStrategies.static) !== 'function') {
        Vue.config.optionMergeStrategies.static = Vue.config.optionMergeStrategies.data;
    }

    Vue.mixin({
        beforeCreate: function () {
            const static = this.$options.static;
            Vue.config.optionMergeStrategies.static(this, static);
        },
    });
}
```

**Comment by Akryum** [comment]
Don't call the option merge strategy in the mixin, it will be applied by Vue automatically. (Keep the previous code.)

**Comment by samuelantonioli** [comment]
Never knew. I don't see that there are any changes necessary then. You can always use `Vue.config.optionMergeStrategies.static` for a custom merge strategy because it's just a normal `$options` property.

So basically just add documentation for it in the README.

**Comment by samuelantonioli** [comment]
## Custom Merge Strategy

Internally, this plugin uses Vue's [$options](https://vuejs.org/v2/api/#vm-options) (specifically `$options.static`). Therefore you can use [custom merge strategies](https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies).

```
Vue.config.optionMergeStrategies.static = function(from_val, to_val) {
    // use another strategy
    //
    // return merged_val
};
```

 - - -

Updated the [README](https://github.com/samuelantonioli/vue-static). Issue resolved in your opinion?

**Comment by Akryum** [comment]
Without `Vue.config.optionMergeStrategies.static = Vue.config.optionMergeStrategies.data` Vue will not merge anything and the static option will be overridden.

**Comment by samuelantonioli** [comment]
Ok, got it.

```javascript
function install(Vue) {
    if (typeof(Vue.config.optionMergeStrategies.static) !== 'function') {
        Vue.config.optionMergeStrategies.static = Vue.config.optionMergeStrategies.data;
    }

    Vue.mixin({
        beforeCreate: function () {
            const static = this.$options.static;
            if (static && typeof(static) === 'function') {
                Object.assign(this, static.apply(this));
            } else if (static && typeof(static) === 'object') {
                Object.assign(this, static);
            }
        },
    });
}
```

**Comment by Akryum** [comment]
👍
