### ISSUE TITLE
SonarQube throws on static() because keyword is reserved

### ISSUE THREAD

**Issue by hoopyfroody** [samuelantonioli/vue-static#4]
SonarQube (a static analysis app we use in our CI pipeline) doesn't know what to do with a function named static and throws a parse error. Considering static is a reserved keyword in strict mode javascript, this makes sense to me, even if vue does not error on it.

I raised an issue with them, but they essentially said it is a won't-fix for them: https://github.com/SonarSource/SonarJS/issues/1113

I realise this is a big change, but would you consider renaming the property? If not, we will have to fork to make it work for us, as we really like the functionality vue-static offers.

**Comment by samuelantonioli** [comment]
Hello @mattixittam,

a custom name for the `static` function is a good idea.

```js
import VueStatic from 'vue-static'
Vue.use(VueStatic, {
    name: 'static_data',
});
```

What do you think? You're free to call the function whatever you like then.
